trigger:
  branches:
    include:
      - main
      - azure-pipelines
    exclude:
      - releases/old*
jobs:
    - job: TerraformInit
    - steps:
      - task: TerraformTaskV4@4
        inputs: null
        provider: azurerm
        command: init
        backendServiceArm: azhabasubscribe01-sp
        backendAzureRmResourceGroupName: az400-vig
        backendAzureRmStorageAccountName: hasstr01
        backendAzureRmContainerName: hasstrcont