# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: az400mlab-pool1
  demands:
  - agent.name -equals az400mlab-vm0

  task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.0.0
