trigger:
  branches:
    include:
      - main
      - azure-pipelines
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: az400mlab-pool1
      demands:
        - agent.name -equals MMD5CG20976RX
    steps:
      - script: echo hello from Windows
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'azhabasubscribe01-sp'
          backendAzureRmResourceGroupName: 'az400-vig'
          backendAzureRmStorageAccountName: 'hasstr01'
          backendAzureRmContainerName: 'hasstrcont'