# specific branch build Trigger
trigger:
  branches:
    include:
    - main
    - azure-pipelines
    exclude:
    - releases/old*


# Tasks
jobs:
- job: Windows
  pool:
    name: az400mlab-pool1
    demands: 
    - agent.name -equals MMD5CG20976RX
  steps:
  - script: echo hello from Windows
  - script: terraform -init